model_type: mace_glass
r_max: 2.0
num_bessel: 10
num_polynomial_cutoff: 2
max_ell: 2
num_interactions: 6
hidden_irreps: "16x0e + 16x1o + 16x1e"
correlation: 3
num_elements: 2
interaction_type: RealAgnosticResidualInteractionBlock
avg_num_neighbors: 50
radial_MLP: [16]
num_outputs: 10
batchnorm: false
bn_momentum: 0.5
