model_type: mace_glass
r_max: 2.0
num_bessel: 10
num_polynomial_cutoff: 2
max_ell: 3
num_interactions: 4
hidden_irreps: "8x0e + 8x1o + 8x1e + 8x2e"
correlation: 3
num_elements: 2
interaction_type: RealAgnosticResidualInteractionBlock
avg_num_neighbors: 20.321
radial_MLP: [16]
num_outputs: 10
batchnorm: true
bn_momentum: 0.5
dropout_p: 0.0
