defaults:
  - model: mace_glass
  - data: shiba
  - training: default

experiment:
  name: ${model.model_type}

wandb:
  entity: luac-inria
  project: MACE
  enabled: true
  debug: false
  group: results
