defaults:
  - model: mace_rmd17_bn
  - data: rmd17
  - training: rmd17

experiment:
  name: rmd17_bn_${data.molecule}_split${data.split}

wandb:
  entity: luac-inria
  project: MACE
  enabled: true
  debug: false
  group: rmd17_bn
